name: Release Notes Verification and AsciiDoc Generation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

env:
  RELEASE_NOTES_JSON_DIR: "docs/modules/user-guide/pages/releases/json"
  RELEASE_NOTES_DIR: "docs/modules/user-guide/pages/releases"

jobs:
  release-notes-updating:
    name: Release Notes Updating
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine whether to skip the release notes check
        id: check-label
        run: |
          echo "## Checking if skip-release-notes-verification label is present :passport_control:" >> $GITHUB_STEP_SUMMARY
          if ${{ contains(github.event.pull_request.labels.*.name, 'skip-release-notes-verification') }}; then
            echo "## Label 'skip-release-notes-verification' is found. Skipping action :no_entry:" >> $GITHUB_STEP_SUMMARY
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Label 'skip-release-notes-verification' is not found. Proceeding with the action :rocket:"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in the release notes
        if: steps.check-label.outputs.skip == 'false'
        id: check-changes
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }})
          echo "## Checking for changes in the release notes :mag:" >> $GITHUB_STEP_SUMMARY
          if echo "$CHANGED_FILES" | grep -q $RELEASE_NOTES_JSON_DIR;
          then
            echo "## Release notes are updated! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
            echo "changes=true" >> $GITHUB_OUTPUT
            CHANGED_FILES=$(echo "$CHANGED_FILES" | grep $RELEASE_NOTES_DIR)
            echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          else
            echo "## Release notes are NOT updated! :x:" >> $GITHUB_STEP_SUMMARY
            echo "changes=false" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install virtualenv
        if: steps.check-label.outputs.skip == 'false' && steps.check-changes.outputs.changes == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Generate AsciiDoc version(s)
        if: steps.check-label.outputs.skip == 'false' && steps.check-changes.outputs.changes == 'true'
        run: |
          source venv/bin/activate
          echo "## Start generating `$GENERATED_RELEASE_NOTES_FILE_NAME` :page_facing_up:" >> $GITHUB_STEP_SUMMARY
          chmod +x generate_asciidoc_release_notes.py
          for file in ${{ steps.check-changes.outputs.changed_files }}; do
            echo "## Generating AsciiDoc file for $file" >> $GITHUB_STEP_SUMMARY
            release_version=$(echo "$file" | grep -oP 'release-notes-\K[0-9]+\.[0-9]+\.[0-9]+')
            ./generate_asciidoc_release_notes.py -r $release_version
          done
          ./generate_asciidoc_release_notes.py
          echo "## AsciiDoc file(s) generated successfully :white_check_mark: at :file_folder: $RELEASE_NOTES_DIR" >> $GITHUB_STEP_SUMMARY

      - name: Git Auto Commit
        if: steps.check-label.outputs.skip == 'false' && steps.check-changes.outputs.changes == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Auto-generate AsciiDoc release notes
          file_pattern: '*.adoc *.yml'
