name: Check Release Notes Updating

on:
    pull_request:
        types:
            - opened
            - synchronize
            - labeled
            - unlabeled

jobs:
    release-notes-updating:
        name: Release Notes Updating
        runs-on: ubuntu-22.04

        outputs:
            skip-check: ${{ steps.skip-check.outputs.skip-check }}
            docs-changed: ${{ steps.docs-check.outputs.docs-changed }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Determine whether to skip the release notes check
              id: skip-check
              run: |
                  echo "## Checking if skip-release-notes-verification label is present :passport_control:" >> $GITHUB_STEP_SUMMARY;
                  SKIP_CHECK=false;
                  if ${{ contains(github.event.pull_request.labels.*.name, 'skip-release-notes-verification') }}; then
                    echo "## skip-release-notes-verification label is present so the verification will be skipped :white_check_mark:" >> $GITHUB_STEP_SUMMARY;
                    SKIP_CHECK=true;
                  fi;
                  echo "skip-check=$SKIP_CHECK" >> $GITHUB_OUTPUT;

            - name: Check for updates in release notes directory
              id: docs-check
              if: ${{ steps.skip-check.outputs.skip-check != 'true' }}
              run: |
                  DOCS_DIR=docs/modules/user-guide/pages/releases
                  if git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | grep -q $DOCS_DIR; then
                    echo "## Release notes are updated! :white_check_mark:" >> $GITHUB_STEP_SUMMARY;
                    echo "docs-changed=true" >> $GITHUB_OUTPUT;
                  else
                    echo "## Release notes are NOT updated! :x:" >> $GITHUB_STEP_SUMMARY;
                    echo "docs-changed=false" >> $GITHUB_OUTPUT;
                    exit 1
                  fi;

            - name: Print Outputs for Debugging
              run: |
                  echo "Output Skip-Check: ${{ steps.skip-check.outputs.skip-check }}"
                  echo "Output Docs-Changed: ${{ steps.docs-check.outputs.docs-changed }}"
