name: Release Notes Verification and AsciiDoc Generation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled
      - unlabeled

env:
  RELEASE_NOTES_DIR: "docs/modules/user-guide/pages/releases"
  GENERATED_RELEASE_NOTES_FILE_NAME: "release-*.adoc"

jobs:
  release-notes-updating:
    name: Release Notes Updating
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine whether to skip the release notes check
        id: check-label
        run: |
          echo "## Checking if skip-release-notes-verification label is present :passport_control:" >> $GITHUB_STEP_SUMMARY
          if ${{ contains(github.event.pull_request.labels.*.name, 'skip-release-notes-verification') }}; then
            echo "## Label 'skip-release-notes-verification' is found. Skipping action :no_entry:" >> $GITHUB_STEP_SUMMARY
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "Label 'skip-release-notes-verification' is not found. Proceeding with the action :rocket:"
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Check for changes in the release notes
        if: steps.check-label.outputs.skip == 'false'
        run: |
          if git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | grep -q $RELEASE_NOTES_DIR; then
            echo "## Release notes are updated! :white_check_mark:" >> $GITHUB_STEP_SUMMARY
          else
            echo "## Release notes are NOT updated! :x:" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Set up Python
        if: steps.check-label.outputs.skip == 'false'
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Generate AsciiDoc version
        if: steps.check-label.outputs.skip == 'false'
        run: |
          echo "## Start generating $GENERATED_RELEASE_NOTES_FILE_NAME :page_facing_up:" >> $GITHUB_STEP_SUMMARY
          chmod +x generate_asciidoc_release_notes.py
          ./generate_asciidoc_release_notes.py
          echo "## $GENERATED_RELEASE_NOTES_FILE_NAME is generated successfully :white_check_mark: at :file_folder: $RELEASE_NOTES_DIR" >> $GITHUB_STEP_SUMMARY

      - name: Git Auto Commit
        if: steps.check-label.outputs.skip == 'false'
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: Auto-generate AsciiDoc release notes
          file_pattern: '*.adoc'
